### ISSUE TITLE
Retrieving schema?

### ISSUE THREAD

**Issue by cyphercider** [dgraph-io/dgraph-js#20]
Modifying the schema with op.setSchema ... client.alter(op) works great.

However, how can I retrieve the dgraph schema?  I tried passing a query of the form:

```
schema {
...
}
```

But it doesn't return results, I assume because a schema query isn't supported by the Txn.query method?

**Comment by pawanrawal** [comment]
You can retrieve the schema using the `/query` endpoint. The result would be in the [Schema](https://github.com/dgraph-io/dgraph-js/blob/master/protos/api.proto#L43) field.

**Comment by cyphercider** [comment]
Thanks @pawanrawal.  To clarify, can I do this with the js client or only the HTTP endpoint?

**Comment by pawanrawal** [comment]
Looks like we just return the [`JSON` result](https://github.com/dgraph-io/dgraph-js/blob/master/src/types.ts#L75) from the client.

@gpahal could we check if `Schema` field has a non-empty response if it does then convert it to JSON and return otherwise return the JSON response? This should be safe to do because we don't allow `schema{}` with other queries so we can't have both.

**Comment by gpahal** [comment]
You can do this with the client. Just use the [`Response#getSchemaList()`](https://github.com/dgraph-io/dgraph-js/blob/9c288baa42b21bbb562e009bf2469d422719e9c0/generated/api_pb.d.ts#L46) method.

**Comment by cyphercider** [comment]
@gpahal got it, thanks!
